import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Poppins } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import PromptProvider from "@/context/PromptContext";
import { SessionProvider } from "next-auth/react";
import AppProvider from "./AppProvider";
import { Toaster } from "@/components/ui/sonner";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});
const montserrat = Poppins({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`$${roboto.variable} ${montserrat.variable} bg-[#111112] antialiased `}
      >
        <AppProvider>
          <Toaster />
          <AppSidebar />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
